// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSctmn4lgrCzAWoU55Dx1LmkFaJwQe4sk',
    appId: '1:291822792746:web:9651fc5990c3799c3c9353',
    messagingSenderId: '291822792746',
    projectId: 'smart-transit-kigali',
    authDomain: 'smart-transit-kigali.firebaseapp.com',
    storageBucket: 'smart-transit-kigali.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSJDHUJhlsPqcsn0L9faKUXkMzhn2zK3E',
    appId: '1:291822792746:android:39c47157ca6dd9e53c9353',
    messagingSenderId: '291822792746',
    projectId: 'smart-transit-kigali',
    storageBucket: 'smart-transit-kigali.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOXys6qF3h24OyZpbynJWP68yKrJCJlUM',
    appId: '1:291822792746:ios:2d658c74a7be00d13c9353',
    messagingSenderId: '291822792746',
    projectId: 'smart-transit-kigali',
    storageBucket: 'smart-transit-kigali.firebasestorage.app',
    iosBundleId: 'com.example.smartTransitKigali',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOXys6qF3h24OyZpbynJWP68yKrJCJlUM',
    appId: '1:291822792746:ios:2d658c74a7be00d13c9353',
    messagingSenderId: '291822792746',
    projectId: 'smart-transit-kigali',
    storageBucket: 'smart-transit-kigali.firebasestorage.app',
    iosBundleId: 'com.example.smartTransitKigali',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSctmn4lgrCzAWoU55Dx1LmkFaJwQe4sk',
    appId: '1:291822792746:web:1a23de6bc1b760243c9353',
    messagingSenderId: '291822792746',
    projectId: 'smart-transit-kigali',
    authDomain: 'smart-transit-kigali.firebaseapp.com',
    storageBucket: 'smart-transit-kigali.firebasestorage.app',
  );
}
